apiVersion: v1
kind: Service
metadata:
  name: {{ include "anything-llm.fullname" . }}
  labels:
    {{- include "anything-llm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "anything-llm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: traffic
      port: {{ .Values.service.trafficPort }}
      targetPort: {{ .Values.service.targetPort }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsPort }}
